### PR TITLE
Add option DOMAIN_NAME

### PR DESCRIPTION
**Pull request by iamluc**

### CODE REVIEW

**Comment by iamluc** [comment]
ping @kevin-verschaeve @blazarecki @Jean-Beru

**Comment by Jean-Beru** [comment]
If I run `docker run -d -e DOMAIN_NAME=test.com,www.test.com my_image` with multiple running containers, it will result in

```
192.168.0.1 test.com www.test.com first_container
192.168.0.2 test.com www.test.com second_container
```

So which container is reached if I go to www.test.com ?

**Comment by iamluc** [comment]
The first one I guess.
But why are you launching several containers withe the same `DOMAIN_NAME` ?

**Comment by Jean-Beru** [comment]
I misunderstood, I thought you ran the docker-hostmanager image. Good feature but you can write your `/etc/hosts` like this :

```
192.168.0.1 test.com www.test.com container
```

instead of

```
192.168.0.1 test.com
192.168.0.1 www.test.com
192.168.0.1 container
```

(tested on the @kevin-verschaeve machine)

**Comment by iamluc** [comment]
Ok. hosts are now on the same line

**Comment by kevin-verschaeve** [comment]
:+1: 
Top !

**Pull request merged**
